language: cpp
before_install:
  - sudo apt-get install wine wput python2 tcl curl
  - git clone https://github.com/nikitakit/ucpp
  - set PATH=$PATH:`pwd`/ucpp/ucpp
  - ucpp setup -t 3130
  - ucpp init
script: ucpp configure && make
