// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static Gyro* drivetrainGyro;
	static SpeedController* drivetrainLeftFront;
	static SpeedController* drivetrainLeftRear;
	static SpeedController* drivetrainRightFront;
	static SpeedController* drivetrainRightRear;
	static Solenoid* shooterIndexer;
	static Solenoid* shooterFlipper;
	static SpeedController* shooterTopShooter;
	static SpeedController* shooterBottomShooter;
	static SpeedController* winchWinch;
	static DoubleSolenoid* armsTelescopes;
	static DigitalInput* tapeTapeLimitSwitch;
	static SpeedController* tapeTape;
	static Compressor* compressorSystemCompressor;
	static DigitalOutput* lightsDigitalOutput1;
	static DigitalOutput* lightsDigitalOutput2;
	static DigitalOutput* lightsDigitalOutput3;
	static DigitalOutput* lightsDigitalOutput4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
