// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#ifndef AUTONOMOUS_COMMAND_H
#define AUTONOMOUS_COMMAND_H

#include "Commands/WaitCommand.h"
#include "Commands/CommandGroup.h"

#include "../Commands/EnableCompressor.h"
#include "../Commands/SpeedAuto.h"
#include "../Commands/SpeedOff.h"
#include "../Commands/Shoot.h"
#include "../Commands/LightsAutoBegin.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutonomousCommand: public CommandGroup {
public:	
	AutonomousCommand();
};

#endif
