// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Drivetrain.h"
#include "../Robotmap.h"
Drivetrain::Drivetrain() : Subsystem("Drivetrain") {
	robotDrive = RobotMap::drivetrainRobotDrive;
	gyro = RobotMap::drivetrainGyro;
	leftFront = RobotMap::drivetrainLeftFront;
	leftRear = RobotMap::drivetrainLeftRear;
	rightFront = RobotMap::drivetrainRightFront;
	rightRear = RobotMap::drivetrainRightRear;
}
    
void Drivetrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());

	SetDefaultCommand(new DriveWithJoysticks());
}

// Put methods for controlling this subsystem
// here. Call these from Commands.
void Drivetrain::TakeJoystickInputs(Joystick* left, Joystick* right) {
	robotDrive->TankDrive(left, right);
}

void Drivetrain::Stop() {
	robotDrive->Drive(0, 0);
}
