// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef LIGHTS_H
#define LIGHTS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Lights: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	
	enum Mode {
		Disabled = 0,
		AutoBegin = 1,
		TeleStart = 2,
		SpinUp = 3,
		SpinDown = 4,
		Fire = 5,
		Red = 6,
		Blue = 7
	};
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DigitalOutput* digitalOutput1;
	DigitalOutput* digitalOutput2;
	DigitalOutput* digitalOutput3;
	DigitalOutput* digitalOutput4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Lights();
	void InitDefaultCommand();
	void SetMode(Mode);
};
#endif
